Ruby on Rails/Rails/Dojo_Dashboard/config/routes.rb
Rails.application.routes.draw do
    root "dojos#index"
    resources :dojos do
        resources :students
    end
    get 'dojos/new' => 'dojos#new'
    get 'dojos/:id' => 'dojojs#show'
    get 'dojos/:id/edit' => 'dojos#edit'
    post 'dojos' => 'dojo#create'
    patch 'dojos/:id' => 'dojo#update'
    delete 'dojos/:id' => 'dojos#destroy'
end

Ruby on Rails/Rails/Dojo_Dashboard/app/models/dojo.rb
class Dojo < ApplicationRecord
  has_many :students. dependent: :destroy

  validates :branch, :street, :city, :state, presence: true
  validates :state, length: { is: 2 }
end

Ruby on Rails/Rails/Dojo_Dashboard/app/models/student.rb
class Student < ApplicationRecord
    belongs_to :dojo
    EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
    validates :first_name, :last_name, presence: true
    validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: EMAIL_REGEX}

    def self.with_dojo student_id
      self.joins(:dojo).where("student.id = ?", student_id).select(:id, :first_name, :last_name, :email, :branch, :dojo_id, created_at)
    end

    def self.cohort student
      self.where("id != ? AND dojo_id = ? AND DATE(created_at) = ?", student.id, student.dojo_id, student.created_at.strftime("%Y-%m-%d"))
    end
end

Ruby on Rails/Rails/Dojo_Dashboard/app/controllers/dojo_controller.rb
class DojoController < ApplicationController
    def index
        @dojos = Dojo.all
    end

    def new
        @dojo = Dojo.new
    end

    def create
        @dojo = Dojo.new(dojo_params)

        if @dojo.save
            redirect_to root_url, notice: "You have successfully created a Dojo!"

        else
          flash[:error] = @dojo.errors.full_messages
          redirect_to :back
        end
    end

    def show
        @dojo = Dojo.find(params[:id])
    end

    def edit
        @dojo = Dojo.find(params[:id])
    end

    def update
        @dojo = Dojo.find(params[:id])

        if @dojo.updated(dojo_params)
            redirect_to root_path, notice: "You have succcessfully updated a Dojo!"

        else
            flash[:errors] = @dojo.errors.full_messages
            redirect_to :back
        end

    def destroy
        Dojo.find(params[:id]).destroy
        redirect_to :root
    end

    private
    def dojo_params
        param.require(:dojo).permit(:branch, :street, :city, :state)
    end
end

Ruby on Rails/Rails/Dojo_Dashboard/app/controllers/student_controller.rb
class StudentController < ApplicationController
    def new
        @dojos = Dojo.all
        @dojo = Dojo.find(params[:dojo_id])
    end

    def create
        @student = Student.new(student_params)

        if @student.save
            redirect_to "dojos/#{student.dojo_id}", notice: "You have successfully created a student!"

        else
            flash[:errors] = @student.errors.full_messages
            redirect_to :back
        end
    end

    def show
        @student = Student.with_dojo(params[:id])
        @cohort = Student.cohort(@student)
    end

    def edit
        @dojos = Dojo.all
        @student = Student.cohort(@student)
    end

    def update
        Student.find(params[:id])

        if @student.update(student_params)
            redirect_to dojo_student_path(@student.dojo_id, @student_id), notice: "You have successfully updated a student!"

        else
            flash[:errors] = @student.errors.full_messages
            redirect_to :back
        end
    end

    def destroy
        Student.find(params[:id]).destroy
        redirect_to :root
    end

    private
    def student_params
        params.require(:student).permit(:first_name, :last_name, :email, :dojo_id)
    end
end

Ruby on Rails/Rails/Dojo_Dashboard/app/helpers/dojo_helper.rb
module DojoHelper
end

Ruby on Rails/Rails/Dojo_Dashboard/app/helpers/student_helper.rb
module StudentHelper
end

Ruby on Rails/Rails/Dojo_Dashboard/app/views/dojo/edit.html.erb
<h1>Editing <%= @dojo.branch %></h1>

<% flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <p><%= e %></p>
    <% end %>
<% end %>

<form action="/dojos/<%= @dojo.id %>" method="post">
    <input type="hidden" name="authenticity_token" value="form_authenticity_token">
    <input type="hidden" name="_method" value="patch">
        <p>
            <label>Branch:</label>
                <input type="text" name="dojo[branch]" value="<%= @dojo.branch %>">
        </p>
        <p>
            <label>Street:</label>
                <input type="text" name="dojo[street]" value="<%= @dojo.street %>">
        </p>
        <p>
            <label>City:</label>
                <input type="text" name="dojo[city]" value="<%= @dojo.city %>">
        </p>
        <p>
            <label>State:</label>
                <input type="text" name="dojo[state]" value="<%= @dojo.state %>">
        </p>
</form>
<%= link to "Home", root_path %> |
<%= link_to "Show", dojo %>

Ruby on Rails/Rails/Dojo_Dashboard/app/views/dojo/index.html.erb
<h1>Listing <%= pluralize(@dojo.count), "Dojo" %></h1>

<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<table>
    <thead>
        <tr>
            <th>Coding Dojo Branch</th>
            <th>Street</th>
            <th>City</th>
            <th>State</th>
            <th>Actions</th>
        </tr>
  </thead>
  <tbody>

    <% @dojos.each do |dojo| %>

        <tr>
            <td><%= dojo.branch %></td>
            <td><%= dojo.street %></td>
            <td><%= dojo.city %></td>
            <td><%= dojo.state %></td>
            <td>
                <%= link_to "Show", dojo %>
                <%= link_to "Edit", edit_dojo_path(dojo) %>
                <%= link_to "Delete", dojo, data: { method: :delete, confirm: "Are you sure you want to delete this item?"} %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= link_to "New Dojo", new_dojo_path %>

Ruby on Rails/Rails/Dojo_Dashboard/app/views/dojo/new.html.erb
<h1>New Dojo</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <p><%= e %></p>
    <% end %>
<% end %>

<form action="/dojos" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <p>
        <label>Branch:</label>
        <input type="text" name="dojo[branch]">
    </p>
    <p>
        <label>Street:</label>
        <input type="text" name="dojo[street]">
    </p>
    <p>
        <label>City:</label>
        <input type="text" name="dojo[city]">
    </p>
    <p>
        <label>State:</label>
        <input type="text" name="dojo[state]">
    </p>
    <input type="submit" value="Create">
</form>

<%= link_to "Back", root_path %>

Ruby on Rails/Rails/Dojo_Dashboard/app/views/dojo/show.html.erb
<h1><%= @dojo.branch %></h1>

<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<p>Address: <%= @dojo.street %></p>
<p>City: <%= @dojo.city %> State: <%= @dojo.state %></p>

<h2>Student Roster</h2>

<table>
    <thead>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Actions</th>
    </thead>
    <tbody>
        <% if @students %>
            <% @students.each do |s| %>
                <tr>
                    <td><%= s.first_name %></td>
                </tr>
            <% end %>
        <% end %>
    </tbody>
</table>

<%= link_to "Home", root_path %> |
<%= link_to "Edit", edit_dojo_path(@dojo) %> |
<%= link_to "Add Student", new_dojo_student_path(@dojo) %>

Ruby on Rails/Rails/Dojo_Dashboard/app/views/student/edit.html.erb
<h1>Editing <%= @student.first_name %> <%= @student.last_name %></h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <p><%= e %></p>
    <% end %>
<% end %>

<form action="/dojos/<%= @student.dojo_id %>/students/<%= @student.id %>" method="post">
    <input type="hidden" name="authenticity_token" value="form_authenticity_token">
    <input type="hidden" name="_method" value="patch">
    <p>
        <label>First Name:</label>
            <input type="text" name="student[first_name]" value="<%= @student.first_name %>">
    </p>
    <p>
        <label>Last Name:</label>
            <input type="text" name="student[last_name]" value="<%= @student.last_name %>">
    </p>
    <p>
        <label>Email Address:</label>
            <input type="text" name="student[email]" value="<%= @student.email %>">
    </p>
    <p>
        <label>Dojo:</label>
            <select name="student[dojo_id]">

                <% @dojos.each do |dojo| %>
                    <% if dojo.id == @student.dojo_id %>
                        <option selected value="<%= dojo.id %>"><%= dojo.branch %></option>
                    <% else %>
                        <option value="<%= dojo.id %>"><%= dojo.branch %></option>
                    <% end %>
                <% end %>
                
    <input type="submit" value="Update">
</form>

<%= link_to "Home", root_path %> |
<%= link_to "#{@student.first_name}", dojo_student_path(@student.dojo_id, @student) %></a>

Ruby on Rails/Rails/Dojo_Dashboard/app/views/student/new.html.erb
<h1>Add New Student</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <p><%= e %></p>
    <% end %>
<% end %>

<form action="/dojos/<%= @dojo.id %>/students" method="post">
    <input type="hidden" name="authenticity_token" value="form_authenticity_token">
    <p>
        <label>First Name:</label>
            <input type="text" name="student[first_name]">
    </p>
    <p>
        <label>Last Name:</label>
            <input type="text" name="student[last_name]">
    </p>
    <p>
        <label>Email Address:</label>
            <input type="text" name="student[email]">
    </p>
    <p>
        <label>Dojo:</label>
            <select name="student[dojo_id]">

                <% @dojos.each do |dojo| %>
                    <% if dojo == @dojo %>
                        <option selected value="<%= dojo.id %>"><%= dojo.branch %></option>

                    <% else %>
                        <option value="<%= dojo.id %>"><%= dojo.branch %></option>
                    <% end %>
                <% end %>

            </select>
    </p>
    <input type="submit" value="Create">
</form>

<%= link_to "Home", root_path %> |
<%= link_to "#{@dojo.branch}", @dojo %>

Ruby on Rails/Rails/Dojo_Dashboard/app/views/student/show.html.erb
<h1><%= "#{@student.branch}'s'" "#{@student.first_name}" "#{@student.last_name}" %></h1>

<% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
<% end %>

<h4>Email: <%= "#{@student.email}" %></h4>
<h3>Cohort</h3>
<table>
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>

        <% @cohort.each do |student| %>

            <tr>
                <td><%= student.first_name %></td>
                <td><%= student.last_name %></td>
                <td><%= student.email %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to "Home", root_path %> |
<%= link_to "Edit", edit_dojo_student_patch(@student.dojo_id), @student.id %>